// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioHub.Blogs.Infrastructure.Context;

#nullable disable

namespace PortfolioHub.Blogs.Infrastructure.Migrations
{
    [DbContext(typeof(BlogsDbContext))]
    [Migration("20260726141700_AddFileNamePropForBlogBlock")]
    partial class AddFileNamePropForBlogBlock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Blogs")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogPostTagLinks", b =>
                {
                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BlogPostId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_BlogPostTagLinks_TagId");

                    b.ToTable("BlogPostTagLinks", "blogs");
                });

            modelBuilder.Entity("PortfolioHub.Blogs.Domain.Entities.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_BlogPosts_CreatedAtUtc");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_BlogPosts_CreatedBy");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_BlogPosts_IsDeleted");

                    b.HasIndex("PublishedAtUtc")
                        .HasDatabaseName("IX_BlogPosts_PublishedAt");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_BlogPosts_Slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_BlogPosts_Status");

                    b.ToTable("BlogPosts", "blogs");
                });

            modelBuilder.Entity("PortfolioHub.Blogs.Domain.Entities.BlogPostAuthor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_BlogPostAuthors_UserId");

                    b.HasIndex("BlogPostId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_BlogPostAuthors_BlogPostId_UserId_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("BlogPostId", "Role", "IsDeleted")
                        .HasDatabaseName("IX_BlogPostAuthors_BlogPostId_Role_IsDeleted");

                    b.ToTable("BlogPostAuthors", "blogs");
                });

            modelBuilder.Entity("PortfolioHub.Blogs.Domain.Entities.BlogPostBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeLanguage")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CodeTitle")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextAlign")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId", "BlockType")
                        .HasDatabaseName("IX_BlogPostBlocks_BlogPostId_BlockType");

                    b.HasIndex("BlogPostId", "Order")
                        .IsUnique()
                        .HasDatabaseName("UX_BlogPostBlocks_BlogPostId_Order_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("BlogPostBlocks", "blogs", t =>
                        {
                            t.HasCheckConstraint("CK_BlogPostBlocks_Order", "[Order] >= 0");
                        });
                });

            modelBuilder.Entity("PortfolioHub.Blogs.Domain.Entities.BlogPostComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId")
                        .HasDatabaseName("IX_BlogPostComments_BlogPostId");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("IX_BlogPostComments_ParentCommentId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_BlogPostComments_UserId");

                    b.HasIndex("BlogPostId", "CreatedAtUtc")
                        .HasDatabaseName("IX_BlogPostComments_BlogPostId_CreatedAtUtc");

                    b.ToTable("BlogPostComments", "blogs");
                });

            modelBuilder.Entity("PortfolioHub.Blogs.Domain.Entities.BlogPostLike", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLiked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LikedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UnLikedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_BlogPostLikes_UserId");

                    b.HasIndex("BlogPostId", "IsLiked")
                        .HasDatabaseName("IX_BlogPostLikes_BlogPostId_IsLiked");

                    b.HasIndex("BlogPostId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_BlogPostLikes_BlogPostId_UserId");

                    b.ToTable("BlogPostLikes", "blogs");
                });

            modelBuilder.Entity("PortfolioHub.Blogs.Domain.Entities.BlogPostReferences", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId")
                        .HasDatabaseName("IX_BlogPostReferences_BlogPostId");

                    b.HasIndex("BlogPostId", "Url")
                        .IsUnique()
                        .HasDatabaseName("UX_BlogPostReferences_BlogPostId_Url_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("BlogPostReferences", "blogs");
                });

            modelBuilder.Entity("PortfolioHub.Blogs.Domain.Entities.BlogPostTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_BlogPostTags_Name");

                    b.ToTable("BlogPostTags", "blogs");
                });

            modelBuilder.Entity("PortfolioHub.Blogs.Domain.Entities.BlogPostView", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FirstViewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastViewAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId")
                        .HasDatabaseName("IX_BlogPostViews_BlogPostId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_BlogPostViews_UserId");

                    b.HasIndex("BlogPostId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_BlogPostViews_BlogPostId_UserId");

                    b.ToTable("BlogPostViews", "blogs", t =>
                        {
                            t.HasCheckConstraint("CK_BlogPostViews_ViewCount", "[ViewCount] >= 1");
                        });
                });

            modelBuilder.Entity("BlogPostTagLinks", b =>
                {
                    b.HasOne("PortfolioHub.Blogs.Domain.Entities.BlogPost", null)
                        .WithMany()
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortfolioHub.Blogs.Domain.Entities.BlogPostTag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortfolioHub.Blogs.Domain.Entities.BlogPostAuthor", b =>
                {
                    b.HasOne("PortfolioHub.Blogs.Domain.Entities.BlogPost", "BlogPost")
                        .WithMany("BlogPostAuthors")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("PortfolioHub.Blogs.Domain.Entities.BlogPostBlock", b =>
                {
                    b.HasOne("PortfolioHub.Blogs.Domain.Entities.BlogPost", "BlogPost")
                        .WithMany("BlogPostBlocks")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("PortfolioHub.Blogs.Domain.Entities.BlogPostComment", b =>
                {
                    b.HasOne("PortfolioHub.Blogs.Domain.Entities.BlogPost", "BlogPost")
                        .WithMany("BlogComments")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortfolioHub.Blogs.Domain.Entities.BlogPostComment", null)
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("PortfolioHub.Blogs.Domain.Entities.BlogPostLike", b =>
                {
                    b.HasOne("PortfolioHub.Blogs.Domain.Entities.BlogPost", "BlogPost")
                        .WithMany("BlogPostLikes")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("PortfolioHub.Blogs.Domain.Entities.BlogPostReferences", b =>
                {
                    b.HasOne("PortfolioHub.Blogs.Domain.Entities.BlogPost", "BlogPost")
                        .WithMany("BlogReferences")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("PortfolioHub.Blogs.Domain.Entities.BlogPostView", b =>
                {
                    b.HasOne("PortfolioHub.Blogs.Domain.Entities.BlogPost", "BlogPost")
                        .WithMany("BlogPostViews")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("PortfolioHub.Blogs.Domain.Entities.BlogPost", b =>
                {
                    b.Navigation("BlogComments");

                    b.Navigation("BlogPostAuthors");

                    b.Navigation("BlogPostBlocks");

                    b.Navigation("BlogPostLikes");

                    b.Navigation("BlogPostViews");

                    b.Navigation("BlogReferences");
                });

            modelBuilder.Entity("PortfolioHub.Blogs.Domain.Entities.BlogPostComment", b =>
                {
                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
