version: "3.8"
name: "PortfolioHub"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: portfolio_db
    env_file:
      - config.env
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "3066:1433"
    volumes:
      - portfolio_db_data:/var/opt/mssql

  backend:
    build: .
    container_name: portfolio_backend
    depends_on:
      - db
    expose:
      - "8090"
    env_file:
      - config.env

  logging:
    image: datalust/seq:latest
    container_name: portfolio_logging
    depends_on:
      - backend
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FLEET_ENABLED=true
    env_file:
      - config.env
    volumes:
      - seq_data:/data
    expose:
      - "5341"
      - "80"

  frontend:
    build: ../frontend
    container_name: portfolio_frontend
    depends_on:
      - backend
    env_file:
      - config.env
    expose:
      - "3050"

  nginx:
    image: nginx:alpine
    container_name: portfolio_nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "8020:8020"
      - "8050:8050"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro

volumes:
  portfolio_db_data: {}  
  seq_data: {}