name: "PortfolioHub"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: portfolio_db
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - portfolio_db_data:/var/opt/mssql
    restart: always 

  backend:
    container_name: portfolio_backend
    depends_on:
      - db
    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    expose:
      - "8090"
    restart: always

  logging:
    image: datalust/seq:latest
    container_name: portfolio_logging
    depends_on:
      - backend
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FLEET_ENABLED=true
    volumes:
      - seq_data:/data
    expose:
      - "5341"
      - "80"
    restart: always 

  frontend:
    container_name: portfolio_frontend
    build:
      args:
        VITE_API_URL: ${VITE_API_URL}
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    expose:
      - "3050"
    restart: always 

  nginx:
    image: nginx:alpine
    container_name: portfolio_reverse_proxy
    depends_on:
      - backend
      - frontend
    restart: always 

volumes:
  portfolio_db_data: {}  
  seq_data: {}