@PortfolioHub.Web_HostAddress = https://localhost:7181
@Auth.Token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTAyODI1NjMsImlhdCI6MTc1MDI4MTY2MywiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InNhZndhdDQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzYWZ3YXRAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI2MzUzOTRjMC1iNGNiLTRjNTAtYTkzMC1mMGE3M2YwZjEzNDIiLCJyb2xlIjoiYWRtaW4iLCJuYmYiOjE3NTAyODE2NjN9.tBAPQKfsdV-G_-83404Dllnkvgp9X0K7Rf7_x-FsSv0
@Auth.RefreshToken = kk2RnLRj7QPcRjYVX1Ea7wqz0Ja+MAiCECqSeTIT2MtrDxkykeAh6jJDFBN799c9N5x6BYGh5nBsXUn4SD02Pg==
// create a new user
POST {{PortfolioHub.Web_HostAddress}}/user
Content-Type: application/json

{
    "username": "safwat4",
    "email":"safwat@gmail.com",
    "password": "Ahmed.99",
    "role": "Admin"
}
###

// login
POST {{PortfolioHub.Web_HostAddress}}/user/login
Content-Type: application/json

{
    "username": "safwat4",
    "password": "Ahmed.99"
}
###
// TestUser: {"username":"testuser", "password":"Testpassword.99"}
// AdminUser: {"username":"Moustafa.Safwat", "password":"Moustafa.99"}
// AdminUser: {"username":"ahmed", "password":"Ahmed.99"}

// refresh token
POST {{PortfolioHub.Web_HostAddress}}/user/refresh-token
Content-Type: application/json

{
    "refreshToken": {{Auth.RefreshToken}}
}
###

// logout
POST {{PortfolioHub.Web_HostAddress}}/user/logout
Content-Type: application/json
Authorization: Bearer {{Auth.Token}}
###

// add a new role
POST {{PortfolioHub.Web_HostAddress}}/role
Content-Type: application/json
Authorization: Bearer {{Auth.Token}}

{
    "name": "Temp"
}
###

// add a new project
POST {{PortfolioHub.Web_HostAddress}}/project
Content-Type: application/json
Authorization: Bearer {{Auth.Token}}

{
    "title": "Wrapper.WPFRevit plu",
    "description": "this project is created to show my power in using revit api.this project is cr.",
    "longDescription": "this plugin is created using C# and best practice.",
    "createdDate": "2024-06-07T00:00:00",
    "categoryId": "72b7c49e-8c0e-47ee-b803-3421bb88b606",
    "videoUrl": "https://sample.com/video.mp4",
    "coverImageUrl": "https://media.licdn.com/dms/image/v2/D5612AQGeyYvEaH-o3A/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1721174071771?e=2147483647&v=beta&t=gsam3lpDXt98b_RqJLUnLm0jzOOnGPz2wt1ycWYQK5s",
    "imagesUrls": ["https://media.licdn.com/dms/image/v2/D5612AQGeyYvEaH-o3A/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1721174071771?e=2147483647&v=beta&t=gsam3lpDXt98b_RqJLUnLm0jzOOnGPz2wt1ycWYQK5s"],
    "skillsId": ["2c767874-561e-4365-a7f7-69e837e3f2b9"],
    "links":
    [
        {
            "providerId":"55555555-5555-5555-5555-555555555555",
            "link":"https://sample.com/video.mp4"
        }
    ]
}
###

// get projects
GET {{PortfolioHub.Web_HostAddress}}/project
Content-Type: application/json

{
    "PageNumber": 1,
    "PageSize": 10
}
### 

// get project by id
GET {{PortfolioHub.Web_HostAddress}}/project/d5c656c5-efb3-4f30-be8d-58ce60e48c58
Content-Type: application/json

###

// delete project by id
DELETE {{PortfolioHub.Web_HostAddress}}/project/3cc7a77a-2785-4069-96ca-bef6aa35a3d9
Content-Type: application/json
Authorization: Bearer {{Auth.Token}}

###

// add gallery
POST {{PortfolioHub.Web_HostAddress}}/gallery
Content-Type: application/json
Authorization: Bearer {{Auth.Token}}

{
    "imageUrl":"https://www.freepik.com/free-vector/blue-circle-with-white-user_145857007.htm#fromView=keyword&page=1&position=0&uuid=f225a35a-4c27-4332-a3fc-0aa408f446f8&query=Avatar",
    "order":1
}
###

// delete gallery
DELETE {{PortfolioHub.Web_HostAddress}}/gallery/69628b05-3601-403a-91cc-6e2054363d60
Content-Type: application/json
Authorization: Bearer {{Auth.Token}}
###

// get galleries
GET {{PortfolioHub.Web_HostAddress}}/gallery
Content-Type: application/json

{
    "PageNumber": 1,
    "PageSize": 10
}
###

// add new category
POST {{PortfolioHub.Web_HostAddress}}/category
Content-Type: application/json
Authorization: Bearer {{Auth.Token}}

{
    "name":"AI/ML"
}
###
// delete category by
DELETE {{PortfolioHub.Web_HostAddress}}/category/11111111-1111-1111-1111-111111111111
Content-Type: application/json
Authorization: Bearer {{Auth.Token}}

###

// get categories
GET {{PortfolioHub.Web_HostAddress}}/category
Content-Type: application/json

###

// add tech skill
POST {{PortfolioHub.Web_HostAddress}}/tech-skill
Content-Type: application/json
Authorization: Bearer {{Auth.Token}}

{
    "name":"test"
}
###

// delete tech skill
DELETE {{PortfolioHub.Web_HostAddress}}/tech-skill/736192c3-f86b-4a4b-9d45-deed642bc327
Content-Type: application/json
Authorization: Bearer {{Auth.Token}}

###

// get tech skill
GET {{PortfolioHub.Web_HostAddress}}/tech-skill
Content-Type: application/json

###

// update tech skill
PUT {{PortfolioHub.Web_HostAddress}}/tech-skill
Content-Type: application/json
Authorization: Bearer {{Auth.Token}}

{
    "id":"ef163968-d8a0-4cc6-8c0a-10b64a5bb7b1",
    "name":"test"
}
###

// Add link provider
POST {{PortfolioHub.Web_HostAddress}}/link-provider
Content-Type: application/json
Authorization: Bearer {{Auth.Token}}

{
    "name":"Youtube",
    "baseUrl":"https://www.Youtube.com/"
}
###

// delete link Provider
DELETE {{PortfolioHub.Web_HostAddress}}/link-provider/70b6ceea-4b42-4f49-b2be-6b12d8a689e9
Content-Type: application/json
Authorization: Bearer {{Auth.Token}}

###

// get link provider
GET {{PortfolioHub.Web_HostAddress}}/link-provider
Content-Type: application/json

###

// update link provider
PUT {{PortfolioHub.Web_HostAddress}}/link-provider
Content-Type: application/json
Authorization: Bearer {{Auth.Token}}

{
    "id":"629e799f-3e08-47c5-83f5-fc13e5da41ba",
    "name":"My-Youtube",
    "baseUrl":"https://www.Youtube.com/"
}
###