@PortfolioHub.Web_HostAddress = https://localhost:7181
@Auth.Token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDkzMDM2MTUsImlhdCI6MTc0OTMwMjcxNSwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InNhZndhdDQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzYWZ3YXRAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI2MzUzOTRjMC1iNGNiLTRjNTAtYTkzMC1mMGE3M2YwZjEzNDIiLCJyb2xlIjoiYWRtaW4iLCJuYmYiOjE3NDkzMDI3MTV9.JQVe3UruFPkQH57P8XpZLTTjfq-LdhLau7du2k9pAdk

// create a new user
POST {{PortfolioHub.Web_HostAddress}}/user
Content-Type: application/json

{
    "username": "safwat4",
    "email":"safwat@gmail.com",
    "password": "Ahmed.99",
    "role": "Admin"
}
###

// login
POST {{PortfolioHub.Web_HostAddress}}/user/login
Content-Type: application/json

{
    "username": "safwat4",
    "password": "Ahmed.99"
}
###
// TestUser: {"username":"testuser", "password":"Testpassword.99"}
// AdminUser: {"username":"Moustafa.Safwat", "password":"Moustafa.99"}
// AdminUser: {"username":"ahmed", "password":"Ahmed.99"}

// add a new role
POST {{PortfolioHub.Web_HostAddress}}/role
Content-Type: application/json
Authorization: Bearer {{Auth.Token}}

{
    "name": "Temp"
}
###

// add a new project
POST {{PortfolioHub.Web_HostAddress}}/project
Content-Type: application/json
Authorization: Bearer {{Auth.Token}}

{
    "Title": "Sample_Projectd",
    "Description": "This is a sample project for testing purposes.",
    "VideoUrl": "https://sample.com/video.mp4",
    "CreatedAt": "2024-06-07T00:00:00"
}
###